#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ksysguard
Version  : 5.13.4
Release  : 1
URL      : https://download.kde.org/stable/plasma/5.13.4/ksysguard-5.13.4.tar.xz
Source0  : https://download.kde.org/stable/plasma/5.13.4/ksysguard-5.13.4.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.2 GPL-2.0
Requires: ksysguard-bin
Requires: ksysguard-data
Requires: ksysguard-license
Requires: ksysguard-locales
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : kdbusaddons-dev
BuildRequires : kinit-dev
BuildRequires : knotifications-dev
BuildRequires : kwindowsystem-dev
BuildRequires : libksysguard-dev

%description
What is KSysGuard?
------------------
KSysGuard is a program to monitor various elements of your system, or any
other remote system with the KSysGuard daemon (ksysgardd) installed.
Currently the daemon has been ported to Linux, FreeBSD, Irix, NetBSD,
OpenBSD, Solaris and Tru64 with varying degrees of completion.

%package bin
Summary: bin components for the ksysguard package.
Group: Binaries
Requires: ksysguard-data
Requires: ksysguard-license

%description bin
bin components for the ksysguard package.


%package data
Summary: data components for the ksysguard package.
Group: Data

%description data
data components for the ksysguard package.


%package dev
Summary: dev components for the ksysguard package.
Group: Development
Requires: ksysguard-bin
Requires: ksysguard-data
Provides: ksysguard-devel

%description dev
dev components for the ksysguard package.


%package doc
Summary: doc components for the ksysguard package.
Group: Documentation

%description doc
doc components for the ksysguard package.


%package license
Summary: license components for the ksysguard package.
Group: Default

%description license
license components for the ksysguard package.


%package locales
Summary: locales components for the ksysguard package.
Group: Default

%description locales
locales components for the ksysguard package.


%prep
%setup -q -n ksysguard-5.13.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1535146533
mkdir clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1535146533
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/ksysguard
cp COPYING %{buildroot}/usr/share/doc/ksysguard/COPYING
cp COPYING.DOC %{buildroot}/usr/share/doc/ksysguard/COPYING.DOC
pushd clr-build
%make_install
popd
%find_lang ksysguard

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ksysguard
/usr/bin/ksysguardd

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.ksysguard.desktop
/usr/share/icons/hicolor/16x16/apps/computer.png
/usr/share/icons/hicolor/16x16/apps/daemon.png
/usr/share/icons/hicolor/16x16/apps/kdeapp.png
/usr/share/icons/hicolor/16x16/apps/kernel.png
/usr/share/icons/hicolor/16x16/apps/ksysguardd.png
/usr/share/icons/hicolor/16x16/apps/running.png
/usr/share/icons/hicolor/16x16/apps/shell.png
/usr/share/icons/hicolor/16x16/apps/unknownapp.png
/usr/share/icons/hicolor/16x16/apps/waiting.png
/usr/share/knotifications5/ksysguard.notifyrc
/usr/share/ksysguard/ProcessTable.sgrd
/usr/share/ksysguard/SystemLoad2.sgrd
/usr/share/kxmlgui5/ksysguard/ksysguardui.rc

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkdeinit5_ksysguard.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/ksysguard/index.cache.bz2
/usr/share/doc/HTML/ca/ksysguard/index.docbook
/usr/share/doc/HTML/de/ksysguard/index.cache.bz2
/usr/share/doc/HTML/de/ksysguard/index.docbook
/usr/share/doc/HTML/en/ksysguard/index.cache.bz2
/usr/share/doc/HTML/en/ksysguard/index.docbook
/usr/share/doc/HTML/et/ksysguard/index.cache.bz2
/usr/share/doc/HTML/et/ksysguard/index.docbook
/usr/share/doc/HTML/it/ksysguard/index.cache.bz2
/usr/share/doc/HTML/it/ksysguard/index.docbook
/usr/share/doc/HTML/nl/ksysguard/index.cache.bz2
/usr/share/doc/HTML/nl/ksysguard/index.docbook
/usr/share/doc/HTML/pt/ksysguard/index.cache.bz2
/usr/share/doc/HTML/pt/ksysguard/index.docbook
/usr/share/doc/HTML/pt_BR/ksysguard/index.cache.bz2
/usr/share/doc/HTML/pt_BR/ksysguard/index.docbook
/usr/share/doc/HTML/ru/ksysguard/index.cache.bz2
/usr/share/doc/HTML/ru/ksysguard/index.docbook
/usr/share/doc/HTML/sv/ksysguard/index.cache.bz2
/usr/share/doc/HTML/sv/ksysguard/index.docbook
/usr/share/doc/HTML/uk/ksysguard/index.cache.bz2
/usr/share/doc/HTML/uk/ksysguard/index.docbook

%files license
%defattr(-,root,root,-)
/usr/share/doc/ksysguard/COPYING
/usr/share/doc/ksysguard/COPYING.DOC

%files locales -f ksysguard.lang
%defattr(-,root,root,-)

